// <auto-generated />
using System;
using INC.EntityFrameworkCore.Test;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace INC.EntityFramworkCore.Test.Migrations
{
    [DbContext(typeof(TContext))]
    [Migration("20180614152610_addTableTeacher")]
    partial class addTableTeacher
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("INC.EntityFrameworkCore.Test.Student", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("id");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("INC.EntityFrameworkCore.Test.Teacher", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<long?>("Studentid");

                    b.HasKey("id");

                    b.HasIndex("Studentid");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("INC.EntityFrameworkCore.Test.Teacher", b =>
                {
                    b.HasOne("INC.EntityFrameworkCore.Test.Student")
                        .WithMany("Teacher")
                        .HasForeignKey("Studentid");
                });
#pragma warning restore 612, 618
        }
    }
}
